### PR TITLE
135-update SRS according to HA

### PR DESCRIPTION
**Pull request by songc120**
## Description

**Summary**: Updated security requirements

**Issue Link**: #135 

## Type of action

- [ ] Bug fix 
- [ ] New feature
- [ ] Requires a documentation update
- [ ] Others: 

## Checklist

- [ ] My code style is consistent with the current project
- [ ] I have done a brief review of my code
- [ ] I have written readable comments
- [ ] I have updated the documentation related to the changes I made
- [ ] I have written reasonable tests and the updated version all passed
- [ ] There should be no potential errors after the changes get merged into main

# Action Required

### CODE REVIEW

**Review by katrina799 — CHANGES_REQUESTED** [review]
There is an issue displaying the content of SRS, the content right now can not be seen and used to link to other sections, please address the issue, thank you! 

Also, I think if you modify the requirements prefix, you should create an issue to update them where those are referenced in our HA as well (after the TA has graded HA)

**Review by katrina799 — APPROVED** [review]
Lgtm, thank you so much!

**Comment by wangq131** [comment]
The icon for the home exceeds the right side of the bar background, should probably adjust the img size or something to fix it? 
Screen Shot 2023-11-01 at 3 22 42 PM

**Comment by wangq131** [comment]
Why is the font size of the professor's name bigger than the other elements' font size? The course code should be more important than professor's name so should be bigger?
Screen Shot 2023-11-01 at 3 25 00 PM

**Review by gaoq20 — APPROVED** [review]

**Pull request merged**
